services:
  - type: web
    name: dynamic-qr-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dynamic-qr-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://your-qr-frontend-url.vercel.app
      - key: PUBLIC_QR_BASE_URL
        value: https://your-qr-frontend-url.vercel.app

databases:
  - name: dynamic-qr-db
    plan: free


